hubzero/framework

- src/Auth/Guard.php
We need this to be able to completely disable local/hub login from the front end.
> Enforce enabled flag for site auth plugin use

- src/Database/Rows.php
I had already implemented the count method...just needed to declare that we were implementing the countable interface.
> Make database rows countable

- src/User/Group/Helper.php
> Updates the database object.

- src/Content/Import/Adapter/Csv.php
- src/Content/Import/Model/Import.php
* Try to catch empty rows in CSV import
* Fix created field name references
> Minor fixes for the content importer

- src/Console/Command/Scaffolding/SearchPlugin.php
- src/Console/Command/Scaffolding/Templates/SearchPlugin.tmpl/%=extension=%.php.tmpl
- src/Console/Command/Scaffolding/Templates/SearchPlugin.tmpl/%=extension=%.xml.tmpl
- src/Console/Command/Scaffolding/Templates/SearchPlugin.tmpl/language/en-GB/en-GB.plg_search_%=extension=%.ini.tmpl
- src/Console/Command/Search.php
new pull request since Travis didn't fire.
> Initial commit of the SearchPlugin scaffolding.

- src/Console/Command/Search.php
Cannot guarantee one process will be finished  before another is spawned  by CRON.
> Introduces locking mechanism for multi-processes.

- src/Search/Adapters/SolrQueryAdapter.php
- src/User/User.php
My apologies I had two changes that I wanted to draw your attention to:
1. Hubzero\Search\Adapters\SolrQueryAdapter - I need to pass a raw string into the filter method to allow for customized geolocational searching.
2. Hubzero\User\User - Removed component-specific references as discussed in our Slack channel.
> important merge

- src/Search/Adapters/SolrQueryAdapter.php
Needed for: https://mygeohub.org/support/ticket/1042
> Adds additional filtering to restrictAccess method.

- src/Database/Relational.php
@zooley please let me know what you think.
> Moves event to all save()'s & calls the onContentSave event.

- src/Geocode/Geocode.php
See https://diagrid.org/support/ticket/943
> Changes the default driver to PDO, the one which we use.

- src/Oauth/Storage/Mysql.php
For more information see: https://nanohub.org/support/ticket/319354
> Removes IP validation in consideration of execution hosts.

- src/Base/Model.php
- src/Database/Table.php
Adding a temporary replacement class for code still using Joomla's
JTable. This can replace it and maintian functonality. Also updating
base model to recognize new Table class.
> Adding temp replacement class for JTable

- src/Database/Query.php
- src/Database/Syntax/Mysql.php
Fixes: https://help.hubzero.org/support/ticket/11150
> Force Limit and Start values to non-negative int

- src/Plugin/Loader.php
Path to a plugin can now be retrieved with `Plugin::path(folder, type)`
> Adding helper method for determining path

- src/Api/Component/Loader.php
- src/Component/ApiController.php
Dynamically generate endpoints for ORM models if a component has not
already implemented its own API. Endpoints are assumed to be plural
forms of singular model names. If component `foo` has model `bar` the
API RUL will be `/api/foo/bars`.
> Dynamically generate endpoints for ORM models

- composer.json
- src/Console/Command/App.php
- src/Console/Command/App/Package.php
- src/Console/Command/App/Repository.php
- src/Console/Output.php
- src/Utility/Composer.php
First round of adding some console commands and a composer utility for
use in muse and elsewhere.  This adds composer/composer as a requirement
for the framework.
> Adding composer commands for muse

- composer.json
Updating and locking the version of composer library used due to a bug
in URL generation.
> Updating dependencies

- src/Database/Rows.php
\#pickRandom returns a new Rows object with the specified
number of rows selected at random from the rows array
\#_setRows sets the $rows attribute of a Rows model to
the provided argument array
> Implement Rows#pickRandom & Rows#_setRows

- src/Search/Adapters/SolrQueryAdapter.php
> [fix] Correct solr restrictAccess on groups

- src/Spam/StringProcessor/NativeStringProcessor.php
- src/Spam/StringProcessor/StringProcessorInterface.php
- src/Spam/Tests/StringProcessorTest.php
Also, some slight reworking of constructor to simplify code.
> [test] Adding test for ascii conversion option

- src/Console/Command/Group.php
Updates path of namespace for \App::get(client) repairing the code pull functionality in the Gitlab integration.
Permanent fix for https://qubeshub.org/support/ticket/1074 .
> Updates path of namespace for \App::get(client)

- src/Database/Table.php
This will allow components that are not yet using Relational models
to update the solr entry.
> [feature] Add onContentSave trigger to \Hubzero\Database\Table

- src/Http/Request.php
Fixes: https://help.hubzero.org/support/ticket/11293
> [fix] Force request values to correct data type

- src/Api/Doc/Generator.php
This also adds components in the `/app` directory and ensures an API
controller follows the correct versioning pattern.
Refs: https://nanohub.org/support/ticket/326046
> [fix] Fixing issue with getting version

- src/Search/Adapters/SolrIndexAdapter.php
Added a way to grab an error message gracefully if solr responded with an error
> [fix] add error handling to solr methods

- src/Utility/Ldap.php
Some style fixes and added methods for getting the list of errors or
success statements.
> [fix] Ensure user name field has a value

- src/Auth/Domain.php
- src/Auth/Link.php
- src/Auth/Link/Data.php
Also adding a model to represent a table for capturing data for each
user/authenticator combination.
> [refactor][feat] Reworked classes to be ORM models

- src/Document/Type/Feed/Atom.php
Fixes: https://help.hubzero.org/support/ticket/11381
> [fix] Fixing bad var scope

- src/Utility/Ldap.php
Fixes: https://qubeshub.org/support/ticket/1145
> [fix] Make sure array key exist before using it

- src/Database/Relational.php
This allows for `$model->attribute = $val;` instead of always using
`$model->set('attribute', $val);`
> [feat] Allow for setting attribs directly

- src/Module/Loader.php
Change to prefer unprefixed directories over prefixed.
> Update module loader preference

- src/Component/Loader.php
Fixes: https://help.hubzero.org/support/ticket/11439
> [fix] Handle cases where data is in unexpected formats

- src/Document/Type/Feed/Atom.php
Fixes: https://help.hubzero.org/support/ticket/11445
> [fix] Declare timezone var used for date calculations

- src/Console/Command/SearchMigration.php
Components can now be indexed for solr via muse searchMigration.
To list a list of options, type: php muse searchMigration help
> [feature] Add muse search Migration for solr.

- src/Utility/Str.php
- src/Utility/Tests/StrTest.php
This fixes some issues with truncating HTML text that contains nested
lists.
Fixes: https://qubeshub.org/support/ticket/1255
> [fix] Reworking to fix issues with nested lists

- src/Content/Migration/Base.php
Removing Joomla-based code and adding more table existence checks. Also
having methods return boolean values in accordance to their docblock.
> [refactor] Removing Joomla code, more table checks

- src/Search/Query.php
Methods were moved to adapters but some got missed so the code was
trying to call nonexistent connection objects (set in the adapters).
Also cleaning up docblock.
> [fix] Call methods on adapter, fixing docblock

- composer.json
- src/User/User.php
Public key should be added to configuration as app.jwt_pub_key.  Currently
only supporting 4096 bit RSA keys, public key should be in OpenSSL PEM
format and base 64 encoded.
> [feat] Add jwt login when running in cloud env

- src/Form/Helper.php
Also some minor reworking to remove usage of Filesystem facae (reducing
dependencies).
> [feat] Translate underscores in field names to directories

- src/Form/Field.php
- src/Html/Grid.php
- src/Html/Toolbar/Button/Confirm.php
- src/Html/Toolbar/Button/Help.php
- src/Html/Toolbar/Button/Link.php
- src/Html/Toolbar/Button/Popup.php
- src/Html/Toolbar/Button/Separator.php
- src/Html/Toolbar/Button/Standard.php
This also includes a fix for external formvalidator script to find required fields. It looks for inputs with a class name of 'required' but the form builder was outputting class name of 'required-field'.
> [refactor][fix] Removing inline JS

- src/Error/Handler.php
This replaces a `debug` property that was unused.
> [feat] Allow a logger to be set on the err handler

- src/Database/Relational.php
Don't attempt to set the primary key or call event hooks if save
isn't successful.
> [fix] Purge cache after successful save

- src/Api/Doc/Generator.php
Fixes: https://mygeohub.org/support/ticket/1367
> [fix] Don't generate docs for disabled components

- src/Api/Request.php
- src/Component/Loader.php
- src/Document/Assets.php
- src/Document/Type/Html/Head.php
- src/Facades/Toolbar.php
- src/Facades/User.php
- src/Form/Rule.php
- src/Form/Rules/Equals.php
- src/Html/Builder/Behavior.php
- src/Html/Builder/Sliders.php
- src/Language/Translator.php
- src/Session/Manager.php
- src/User/Group/Helper.php
- src/User/Password.php
- src/User/Profile/Helper.php
- src/Utility/Cookie.php
- src/Utility/Uri.php
> [fix] Removing remnants of Joomla

- src/Message/Component.php
- src/Module/Loader.php
* Module query fix is for datetime columns' default being changed to NULL
* Messaage fix is for MySQL only_full_group_by mode
> [fix] Fixing queries

- src/Form/Fields/Menuitem.php
Included helper changed location. Added a better file_exists check to
avoid catastrophic failures.
> [fix] Fixing include path

- src/Image/Processor.php
Try to catch fatal errors and return an error message instead when
trying to work with bad or corrupted images.
> [fix] Handle bad images more elegently

- src/Document/Type/Html/Head.php
- src/Html/Builder/Behavior.php
- src/Html/Toolbar/Button/Help.php
Refs: https://github.com/hubzero/hubzero-cms/commit/f4757bf760eaf98391a97d5c3e035517eabbe398
> [refactor] Renaming JS namespace to Hubzero

- src/Html/Toolbar/Button/Popup.php
Only append the root path to relative URLS that don't already have it.
> [fix] Check URL for existing root path

- src/Database/Relational.php
The facade isn't always defined. Use direct class instead.
> [fix] Don't use facade.

- src/Html/Builder/Behavior.php
Fixes: https://nciphub.org/support/ticket/1589
> [fix] Don't treate text in parentheses as formulas

- src/Database/Relational.php
This adds a helper method to get the table's column definitions, caching
it to avoid multiple database hits, and a method for getting the default
value of a column. In adding these methods, some refactoring to simplify
code.
> [feat][refactor] Methods for tbl cols and col default

- src/Message/Component.php
Fixes: https://nanohub.org/support/ticket/350065
> [fix] Get distinct component values

- src/Form/Fields/Select.php
Refs: https://github.com/hubzero/hubzero-cms/pull/1125
Fixes: https://hubicl.org/support/ticket/123
> [fix] Set value to default if no value passed

- src/Plugin/Plugin.php
Refs: https://help.hubzero.org/support/ticket/11843
Refs: https://github.com/hubzero/hubzero-cms/pull/1136
> [maint] Finally removing deprecated methods

- src/Http/Request.php
When declaring the type of value being retrieved (int, string, cmd, etc)
flatten anything that's not suppossed to be an array. This prevents
errors with possible input tampering such as `id[][]=9` with
`Request::getInt('id', 0);`
Fixes: https://help.hubzero.org/support/ticket/11858
> [fix] Flatten arrays when type casting

- src/Item/Comment.php
Was previously reporting created variable.
> [fix] Modified method now reports modified var

- src/Base/ClientDetector.php
Prior version included unused (and mostly useless) code. This simplifies
the client detection and cleans up some comments that simply didn't make
sense.
> Clean up clientdetector
