hubzero/framework

src/Api/Response.php
src/Api/Response/JsonpCallable.php

Problem found by Adam involving getting a JSON response wrapped in a function for cross site requests

[API] Don't JSON encode the JSON-P wrapping for wrapped calls

---

src/Content/Migration.php
src/Form/Fields/Password.php

Previous version of code would attempt to load any file found in the `hooks` directory and treat it as a PHP file containing a class. So, even a JS or `something.php.bak` file would attempted to be executed and throw errors. This change only looks for PHP files.

Only scan and load migraiton hooks that are PHP files

---

src/Utility/Number.php

Empty string was returned for files of size 0,  a formatted string should always be returned (maybe unless a negative size is asked to be formatted...?)

When asked to format a number, format 0 as well

---

src/Filesystem/Collection.php

`$uniqueId` was used further down int he code but never defined.

[MYGEOHUB][#1187] Adding missing var declaration

---

composer.json

no-api means that it will clone the repo to extract metadata from the git metadata instead of using the github API

Adding no-api flag

---

src/Api/Component/Loader.php
src/Component/View.php
src/View/View.php

* Changes usage of JPATH_COMPONENT to PATH_COMPONENT and some minor
reworking of the API component loader to reduce redundancy and simplify
some code.
* Allows for finding of views not in `tmpl` subdirectory.

Remove usage of deprecated Joomla constant

---

src/Routing/Router/Rules.php

Allow for a routing rule to be something a callable other than a Closure
and execute it properly.

Allow routing rules to be callables

---

src/User/Picture/File.php
src/User/Picture/Identicon.php
src/User/Picture/Initialcon.php
src/User/Picture/Namedfile.php

This means the link is not tied to a specific session, allowing it to
be used in emails and the image to be cached by the browser.

Serve user pictures as public files

---

src/Console/Command/User/Terms.php

Clear terms from users as well as xprofiles (deprecated) table. Check
for existence of tables and field on tables first.

Clear terms from users table

---

src/Console/Command/Repository/Flavor.php

A fix I've been manually putting into packages for months.
A previous commit to fix the muse flavorizer failed to actually pass the sql string to setQuery()

actually pass the sql statement to setQuery()

---

providers/LogServiceProvider.php
src/Log/Manager.php
src/Log/Writer.php

Rather than passing the entire App object to the Manager class, we now
only pass an option default log path and optionally set a dispatcher
for the individual config of each logger (rather than assuming the
dispatcher set on the App object).

[refactor] Reducing dependencies and more config options

---

composer.json
src/Console/Command/Extension.php

`muse extension <command>` was broken, not able to find App.
composer/composer had a fix submitted in 1.6.3 that we need (dealing with URL generation for Gitlab packages)

Namespace fix and update to dependencies

---

src/Form/Fields/Language.php
src/Language/Translator.php

The `getList()` method on Translator would always default to the
current client. These changes allow fo specifying a specific client,
defaulting to old behavior if no client is specified. Fixes issue with
specifying available languages for users for 'site' client.

[fix] List languages for specified client

---

src/Api/Component/Loader.php

This fixes an issue where visiting the api url for a non-existent
component would still assume the component did exist and result in a 500

[fix] Make sure non-existent components throw 404

---

src/Utility/Composer.php

Solving the dependency graph problem takes a lot of memory, so when
invoking composer we need more memory.
Refs: https://github.com/composer/composer/issues/5915

Bumping memory limit on single script

---

src/Utility/Composer.php

When packagist is enabled, we can't list *all* available packages.
This should check to ensure we're not attempting to do that.

[fix] Don't try to list too many packages

---

src/Search/Adapters/SolrQueryAdapter.php

Solr would throw a 414 due to a query being too long.
The postbigrequest plugin addresses this by sending the request via POST
instead of GET.
[fixes] https://purr.purdue.edu/support/ticket/1601
https://cdmhub.org/support/ticket/1608

[fix] Add Solr plugin to allow for long query strings

---

src/Database/Query.php
src/Database/Relational.php
src/Database/Syntax/Mysql.php

When calling `paginated()` on a query, the cloned query used for
generating a record total would include all the `select` values, meaning
the query would return not just a count but also all the records. This
now clears all previous select values so it only returns the count.

[refactor] Count query only selects a count

---

src/Console/Command/App/Package.php

Have app commands all *only* accept '--package=' style arguments, some
allowed simply adding a package name as the final argument and some did
not, and some only accepted it as the final argument.

Be consistent in calling a command

---

src/Image/Processor.php

PHP 5.6 has issues reading EXIF data, so try to catch any errors
thrown and proceed a little mroe gracefully.
Refs: https://bugs.php.net/bug.php?id=72914
Refs: https://bugs.php.net/bug.php?id=72819
Fixes: https://smarteragriculture.org/support/ticket/232

[fix] Try to catch EXIF read errors

---

src/Auth/Link.php

This could caus entries to not be properly deleted which, in turn,
breaks account linking.

[fix] Fixing misnamed var

---

src/User/User.php

Sometimes the givenName, middleName, and surname are not set but the
overall name of the user is set.  This allows access to those parts
based on how the admin interface displays them (and subsequently updates
them).

Check if name parts need to be parsed and do so

---

src/Html/Builder/Asset.php
src/View/Helper/Icon.php

These helpers take two arguments: a symbol name, and hide from screen
readers or not. Symbol name directly maps to a file representing the
desired icon. Icons are in `CORE/assets/icons` but can be overridden
with a `APP/templates/{template}/html/icons` directory.

[feat] Adding helpers for displaying core SVG icons

---

src/Spam/Tests/CheckerTest.php

A string processor can be added to the checker to catch, remove, or
transform potentially inappropriate characters or words. This adds a
test where the string ptocessor functioning correctly is integral to the
content being properly detected as spam.

[test] Ensure string processor is used

---

src/Filesystem/Entity.php

Dotfiles come through with an empty filename and a populated extension

[fix] Fix displayName for dotfiles

---

src/Error/Renderer/Api.php
src/Error/Renderer/Notification.php
src/Error/Renderer/Page.php
src/Error/Renderer/Plain.php
src/Error/RendererInterface.php

PHP 5.6 expects an object of type `Exception` whereas PHP 7 expects type
`Throwable`. To be compatible with both, we simply remove the type
hinting. May re-introduce once everything is on PHP 7.

[fix] Adjusting for PHP 5.6 to 7 compatibility

---

src/Content/Import/Model/Import.php

This fixes an issue where the import record could inadvertently get
a new Run record each time `currentRun()` was called, causing the
`processed` field to never be incremented.

[fix] Fixing issue with getting current run

---

src/Password/CharacterClass.php

Only arrays and objects that implement countable are countable in 7.2.
http://us3.php.net/manual/en/migration72.incompatible.php#migration72.incompatible.warn-on-non-countable-types

[fix] Compatibility issue with PHP 7.2

---

composer.json
src/Content/Import/Adapter/Excel/Reader.php

This adds the PhpSpreadsheet library (moved from hubzero-cms) and updates the Excel importer adapter to use it.

[refactor] Use PhpSpreadsheet instead of PhpExcel

---

src/Html/Toolbar/Button/Popup.php

Using `Request::base()` works fine for master, where the admin directory
no longer exists. Base and root are the same in that case. But, on 2.2
where the admin directory still exists, this can cause 'administrator'
to appear twice in the URL (due to being passed through `Route::url()`).
Fixes: https://purr.purdue.edu/support/ticket/1966

[fix] Use root instead of base

---

src/Utility/Sanitize.php

I'd like to extract the steps below from the Sanitize::html function to an HTML purifier factory class, but I'm unsure of where to put such a factory.
- Creation of the HTML purifier configuration
- Updating of the HTML purifier white list
- Creation of the HTML purifier
[Single Responsibility Principle](https://en.wikipedia.org/wiki/Single_responsibility_principle)

Refactor sanitize

---

src/Filesystem/Entity.php

This change ensures the new filename has a name and extension (getName
only returns the name without extension from Google Drive adapter)

[fix] Fix moving files for Google Drive

---

src/Search/Adapters/SolrIndexAdapter.php

Solarium was expecting a nest of arrays, so this method
will convert objects to arrays.

[fix] Ensure array of nested objects is converted to array

---

src/Session/Helper.php
src/Session/Manager.php

Previous helper method would end up invoking __construct on the
configured session store causing an error in PHP 7.2.  This uses the
already instantiated session store.

[refactor] Add session store getter and use it

---

src/Database/Relational.php

Sometimes it is prefferable for the query automatically initiated by a
model to use an alias for the table name. This allows for defining an
alias for all queries or for setting one and re-initializing the query
with the set alias.

[feat] Allow for aliasing table in internal query

---

composer.json

The JWT library is being moved to the master branch of the CMS which has
a dependency of PHP 7. The current production branch of 2.2 has a
dependency of php 5.6 which causes composer to not be able to resolve
an installable set of packages.

[fix] Moving to CMS composer due to  dependencies

---

src/Image/Processor.php

When images with transparent backgrounds generated a thumbnail,
the thumbnail background would default to black causing viewablity
issues.
fixes: https://qubeshub.org/support/ticket/1366

[fix] Thumbnails now generate with proper transparent background

---

src/Database/Driver.php
src/Database/Driver/Mysql.php
src/Database/Driver/Pdo.php
src/Database/Driver/Pgsql.php
src/Database/Driver/Sqlite.php

Adds MySQL, Postgres, and SQLite drivers that extend the PDO driver.
Fallback code has to assume, for now, that if the dbtype is set to 'pdo'
then use 'mysql'.

[refactor] Refactoring to support more PDO dbs

---

src/Error/Handler.php

This fills up logs pretty fast. Especially with bots crawling things.

[fix] Don't log 404s and 403s

---

src/Database/Driver/Mariadb.php
src/Database/Syntax/Mariadb.php

MariaDB is a fork of MySQL and is compatible with MySQL's syntax. So,
until it deviates or custom functionality is needed, it just extends the
MySQL classes.

[feat] Adding driver and syntax for MariaDB

---

src/Activity/Recipient.php
src/Item/Announcement.php

Minor changes to handle datetime columns default value being `null` (in
compliance with MySQL strict mode).

[refactor] Handle datetime col default being null

---

.travis.yml

Caching the composer dependencies should reduce build time, and
prefer-dist should reduce the build size by not grabbing the full source
for all dependencies

[refactor] Updating travis build

---

src/Content/Migration/Base.php

The checked_out_time column may have a different default value
depending upon when migrations get run. So, avoid the issue all together
by not specifying it and let the database handle it.

[fix] Removing checked_out_time column from queries

---

src/Database/Exception/UnsupportedSyntaxException.php
src/Database/Query.php
src/Database/Syntax/Mysql.php
src/Database/Syntax/Sqlite.php
src/Database/Tests/QueryTest.php

* Adds shortcut helper methods in the query builder for the types of
SQL joins that can be performed. Note: SQLite does not support right
or full joins.
* Adds a `clear($clause)` method for resetting portions of a Query.

[feat] Adding `join` helpers and `clear` method

---

src/Pagination/Views/paginator.php

The core CMS javascript attaches event handlers to the paginator's
elements.

[refactor] Removing inline JS for admin paginator

---

src/Facades/Toolbar.php

This allows for adding a button that prompts for confirmation before
executing a task.

[feat] Adding `confirm()` toolbar button

---

src/Content/Moderator.php

In most cases, this won't change the URL. But, in some odd setups, such
as running a hub in a sub-directory, this fixes improper /files URLs.

[fix] Add the root path to `/file/` URLs

---

src/Filesystem/Entity.php

html files were incorrectly attempting to use Hubzero\Facade\Html
since it didn't correctly return false when checking for special
types.
fixes: https://qubeshub.org/support/tickets/1405

[fix] check for file instead of class to prevent Facade fallback

---

src/User/Password.php

This method is needed to be public so it can be used to replace a Joomla
method of similar functionality (called in com_members).

[refactor] Making public so it can be used elsewhere

---

src/Filesystem/Macro/EmptyDirectory.php

Paths for items returned from `listContents` are relative to the base
path passed to that method. So, said base path needs to be prepended to
the paths passed to the delete methods for them to work.

[fix] Pass full path to delete methods

---

src/Html/Toolbar/Button/Confirm.php

Escaping is unnecessary as text is no longer directly output to JS.
Fixes: https://habricentral.org/support/ticket/853

[fix] Don't escape single quotes

---

src/Database/Table.php

Applying the same change for Relational models to Tables. This sets
the default value for `checked_out` and `checked_out_time` based on the
table's schema rather than assuming the values.

[fix] Get default column values from schema

---

src/Plugin/OauthClient.php

If the old com_users exists, then use redirect URIs for it. Otherwise
go to com_login. This should provide time for updating 3rd party configs
until we're ready to remove com_users entirely.

[fix] Backwards compatibility for redirect URIs

---

src/Base/ClientDetector.php

When on the home page, the URL segment is empty, which will match the
Cli client type. Cli should only ever be matched in the context of
being run from the command line.
Todo: Move client matching to a method on the client objects?

[fix] Avoid web home page matching Cli client

---

src/Database/Driver/Pgsql.php

The validation of the PDO dsn string is incorrect, I assume was based on "sqlite:" (7 characters)

pgsql dsn header length fixed

---

src/Console/Arguments.php
src/Console/ArgumentsServiceProvider.php

Muse can now discover commands from components. Given:
`core/components/com_cron/commands/run.php`
Muse command:
`muse cron:run {task}`
Command pattern is `muse {component}:{command} {task} {options}`
A little ugly but necessary for prefixed extensions. Once all extensions
are unprefixed (e.g. `components/groups` instead of
`components/com_groups`), autoloading should take over and these new
lines won't be necessary.

Allow muse commands to be run from components
